config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',           to: 'static_pages#help'
  get  '/about',          to: 'static_pages#about'
  get  '/contact',        to: 'static_pages#contact' 
  get  '/signup',         to: 'users#new'
  post '/signup',         to: 'users#create'
  get  '/login',          to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get  '/createQuiz',     to: 'quizzes#new'
  post '/createQuiz',     to: 'quizzes#create'
  get  '/listQuiz',       to: 'quizzes#list'
  get  '/createQuestion', to: 'questions#new'
  post '/createQuestion', to: 'questions#create'
  get  '/createAnswer',   to: 'answers#new'
  post '/createAnswer',   to: 'answers#create'
  get  '/takeQuiz',       to: 'quizzes#take'
  post '/takeQuiz',       to: 'quizzes#take'
  get  '/showQuiz',       to: 'quizzes#show'
  get  '/results',        to: 'scores#show'
  post '/results',        to: 'scores#show'
  get  '/contact-me',     to: 'messages#new', as: 'new_message'
  post '/contact-me',     to: 'messages#create', as: 'create_message'
  get  '/detailedResults',to: 'scores#showDetailed'
  post '/detailedResults',to: 'scores#showDetailed'

  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :quizzes,             only: [:create, :destroy]
  resources :questions
  resources :answers
  resources :relationships,       only: [:create, :destroy]
  
  # Redirect to error page if invalid url
  get  '*path',           to: 'static_pages#error'
  
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :scores, dependent: :destroy
  validates :title, presence: :true
  validates :user_id, presence: :true
  validates :category, presence: :true
  default_scope -> { order(created_at: :desc) }
  
  def self.search(search)
    where("title LIKE ? OR user_id LIKE ? OR category LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end
  
  def self.quizzes_by_category(category)
    where("category LIKE ?","%#{category}%")
  end
  
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def index
    if params
      uid = User.where("name LIKE ?", "%#{params[:search]}%").first
      if uid
        @quizzes = Quiz.search(uid.id).order("created_at DESC")
      else
        @quizzes = Quiz.search(params[:search]).order("created_at DESC")
      end
    else
      @quizzes = Quiz.all.order('created_at DESC')
    end
  end
  
  def new
    @quiz = Quiz.new
  end
  
  def show
    @quiz = Quiz.find(params[:id])
  end
  
  def create
    @quiz = current_user.quizzes.build(quiz_params)
    if @quiz.title == nil
      @quiz.title = ""
    end
    if @quiz.title.downcase == 'test' 
      cumulative(@quiz)
    elsif @quiz.save
      redirect_to createQuestion_url(quiz_id: @quiz.id)
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def take
    @q = Quiz.find(params[:quiz_id])

    if !Question.where(quiz_id: @q.id, id: params[:question_id]).empty?
      @question = Question.find(params[:question_id])
      @answers = Answer.where(question_id: @question.id)
      @questionNum = 1 + params[:question_id].to_i - Question.where(quiz_id: params[:quiz_id]).first.id
      @totalQuestions = Question.where(quiz_id: params[:quiz_id]).count.to_i
    end

    @user = current_user

    if params[:answer_id] != nil
      if Score.where(quiz_id: params[:quiz_id], user_id: @user.id, question_id: params[:question_id].to_i - 1).exists?

        @score = Score.find_by(quiz_id: params[:quiz_id], user_id: @user.id, question_id: params[:question_id].to_i - 1)

        if Answer.find(params[:answer_id]).correct?
          @score.value = 1
        else
          @score.value = 0
        end

        @score.save

      else
        if Answer.find(params[:answer_id]).correct?
          Score.new(quiz_id: params[:quiz_id], user_id: @user.id, question_id: params[:question_id].to_i - 1, value: 1).save
        else
          Score.new(quiz_id: params[:quiz_id], user_id: @user.id, question_id: params[:question_id].to_i - 1, value: 0).save
        end
      end
    end

    if Question.where(quiz_id: @q.id, id: params[:question_id]).empty?
      redirect_to results_url(quiz_id: @q.id), method: :post
    end

  end
  
  def destroy
     @quiz.destroy
     flash[:succcess] = "quiz deleted"
     redirect_to  root_url
  end
      
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:title, :category)
    end
    
    def correct_user
       @quiz = current_user.quizzes.find_by(id: params[:id])
       redirect_to root_url if @quiz.nil?
    end
    
    def cumulative(quiz)
      quiz = current_user.quizzes.build(quiz_params)#create new quiz in server, not db
      #flash[:notice] = quiz.category
      if quiz.save # save to db
        questions_used = [] #set local tracking array so q's dont repeat
        possible_question_ids = Question.where(quiz_id: Quiz.where(category: quiz.category, user_id: current_user.id)).ids # get array of id's of questions in category for new quiz
        while questions_used.count <= possible_question_ids.count #as many qs in category, does not scale!!!
          current_id = possible_question_ids.sample #pull id from random index
          if !(questions_used.include?(current_id)) #is id already used?
            questions_used.push(current_id) #push on to tracking array
            possible_question_ids.delete(current_id)
            new_question = Question.find(current_id) #get existing question with matching id
            @random_question = quiz.questions.new(title: new_question.title) #create a new identical question for the test
            if @random_question.save #save the new question
              random_answers = Answer.where(question_id: current_id) #add all answers to this new question
              random_answers.each do |ra|
                @new_answer = @random_question.answers.new(content: ra.content, correct: ra.correct)
                if !@new_answer.save
                  flash[:notice] = 'random quiz not created!'
                end
              end
            end
          end
        end
        redirect_to root_url
        flash[:succcess] = 'test created'
      else
        flash[:notice] = 'quiz not saved'
      end
    end
  
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(quiz) do |f| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :question_ids %>
    <%= f.number_field :question_ids %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
 <li id="quiz-<%= quiz.id %>">		
  <%= link_to gravatar_for(User.find(quiz.user_id), size: 50), User.find(quiz.user_id) %>		
  <span class="user"><%= link_to User.find(quiz.user_id).name, User.find(quiz.user_id) %><br /></span>		
  <span class="category"><%= quiz.category %></span>	
  <span class="title"> <%= quiz.title %> - <%= link_to "take this quiz", takeQuiz_path(quiz_id: quiz.id, question_id: Question.where(quiz_id: quiz.id).first) %></span>	
    <%= link_to 'Show Results', results_url(quiz_id: quiz.id) %>
    
    <% if current_user?(quiz.user) %>
       
      <%= link_to "delete", quiz, method: :delete,		
                                  data: { confirm: "Are you sure you want to delete this quiz?" } %>	<br>
    <% end %>  
    <span class="timestamp">		
    Posted <%= time_ago_in_words(quiz.created_at) %> ago.<br />
  </span>		
</li>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>
  <ol class="quizzes">
    <%= render @quizzes %>
  </ol>
  
  
<br>

<%= link_to "New Quiz", new_quiz_path %>

app/views/quizzes/list.html.erb
<div class="col-md-8">
    <% @quizzes = Quiz.all %>
      <h3>Quizzes</h3>
      <%= form_tag quizzes_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
      <ol class="quizzes">
        <%= render @quizzes %>
      </ol>
</div>

app/views/quizzes/new.html.erb
<% provide(:title, 'New Quiz') %>
<h1>New Quiz</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@quiz) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :title%>
      <%= f.text_field :title, class: 'form-control', :required => 'required' %>
      <%= f.label :category%>
      <%= f.text_field :category, class: 'form-control', :required => 'required' %>
      <%= f.submit "Create the Quiz", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="col">
      <div class="col-md-8">
        <h3>Score history for <%= @quiz.title %></h3>
        <p>
        <strong>Created By:</strong>
        <%= User.find(@quiz.user_id).name %>
      </p>
        <ol class="list-group">
          <% Score.where(quiz_id: @quiz.id).each do |s| %>
            <%= User.where(id: s.user_id).first.name %>
            <%= ((1.0 * s.value / Question.where(quiz_id: s.quiz_id).count) * 100) %><br />
            
            <% end  %>
        </ol>
      </div>
  </div>

<%= link_to 'Back', listQuiz_path %>

app/views/quizzes/take.html.erb
<h1><%= @q.title %></h1>

<div class="row">
  <aside class="col-md-8">
    <section class="user_info">
      <h1>
        Question <%= @questionNum %> out of <%= @totalQuestions %><br><br><br>
        <%= @question.title %><br><br>
        <% @answers.where(question_id: @question.id).each do |a| %>
            <%= link_to a.content, takeQuiz_path(quiz_id: @q.id, question_id: @question.id + 1, answer_id: a.id), class: "btn btn-lg btn-default" %>
          <br><br>
        <% end %>
      </h1>
    </section>
  </aside>
</div>