config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',           to: 'static_pages#help'
  get  '/about',          to: 'static_pages#about'
  get  '/contact',        to: 'static_pages#contact' 
  get  '/signup',         to: 'users#new'
  post '/signup',         to: 'users#create'
  get  '/login',          to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get  '/createQuiz',     to: 'quizzes#new'
  post '/createQuiz',     to: 'quizzes#create'
  get  '/listQuiz',       to: 'quizzes#list'
  get  '/createQuestion', to: 'questions#new'
  post '/createQuestion', to: 'questions#create'
  get  '/createAnswer',   to: 'answers#new'
  post '/createAnswer',   to: 'answers#create'
  get  '/takeQuiz',       to: 'quizzes#take'
  post '/takeQuiz',       to: 'quizzes#take'
  get  '/showQuiz',       to: 'quizzes#show'
  get  '/results',        to: 'scores#show'
  post '/results',        to: 'scores#show'
  get  '/contact-me',     to: 'messages#new', as: 'new_message'
  post '/contact-me',     to: 'messages#create', as: 'create_message'
  get  '/detailedResults',to: 'scores#showDetailed'
  post '/detailedResults',to: 'scores#showDetailed'

  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :quizzes,             only: [:create, :destroy]
  resources :questions
  resources :answers
  resources :relationships,       only: [:create, :destroy]
  
  # Redirect to error page if invalid url
  get  '*path',           to: 'static_pages#error'
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #@quiz = current_user.quizzes.build if logged_in?
    if logged_in?
      @quiz = current_user.quizzes.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @feed_items.each do |item|
        @qid = item.id
        @questions = Question.where(quiz_id: @qid)
        @answers = Answer.where(question_id: @questions)
        if(@answers.empty?)
          item.destroy
        end
      end
    end
  end
  
  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This web app is an opportunity for you to test your knowledge on a variety of things. 
  Feel free to make a quiz yourself, and see how well people do. 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    Please don't contact me :(
</p>

app/views/static_pages/error.html.erb
<% provide(:title, "Uh oh!") %>
<div class="center jumbotron">
  <h2>An Error has occured for the url: <%= request.fullpath %> </h2>

  <%= link_to "Return Home", root_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Not real sure what to write here :(
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="col">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <%= link_to "Search for Quiz by Keyword", listQuiz_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Create a Quiz", createQuiz_path, class: "btn btn-lg btn-primary" %>
      <% @rand_id = Quiz.pluck(:id).sample %>
      <%= link_to "Take a Random Quiz", takeQuiz_path(quiz_id: @rand_id, question_id: Question.where(quiz_id: @rand_id).first), class: "btn btn-lg btn-primary" %>
    </aside>
  </div>
  <div class="col">
    <div class="col-md-8">
      <h3>Quiz Feed</h3>
      <%= form_tag quizzes_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>

    <div class="center jumbotron">
      <h1>Welcome the Quiz App!!!!!</h1>
    
      <h2>
       This is the home page for our Quiz App
      </h2>
    
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>    